### ISSUE TITLE
Beds don't work

### ISSUE THREAD

**Issue by VexedPanda** [LexManos/DwarfCraft#1]
As of the 1.5 update, it appears that trainers are counting as awake players and preventing beds from transitioning to daytime.

**Comment by LexManos** [comment]
Fixed in: https://github.com/LexManos/DwarfCraft/commit/3ae9d14da6e002be74e3b64260354d6c9342a31a

**Comment by VexedPanda** [comment]
I just upgraded to 1.08 and beds still do not advance to day time.

**Comment by LexManos** [comment]
I dont know what wrong with you but I just tested on 1.08, and beds work perfectly fine.
